# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a76dc1e1c2b05fa60132c7f6efcc5cbed1da228bdcfb9f4ff905de3473bde662e8c301264e52f5a2a2c744c34e26c76af89d7999887991f53e24b233e8955c7

test:
  secret_key_base: 2b60d143d8515a3da739e698f082937bdd0b3cd5b632a15a67b5eacb503dfb7ff805928ef63cdf4cf5d0d0387731f81249d03ea8ac8f480592ac18d0bdb7500a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
